apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
{{- if .Values.global.labels }}
{{ toYaml .Values.global.labels | indent 4 }}
{{- end }}
  annotations:
    external-dns.alpha.kubernetes.io/ttl: "60"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.networking.dns }}
    kubernetes.io/ingress.class: {{ .Values.networking.ingressClass }}

    {{- if .Values.networking.tls }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.networking.tls.clusterIssuer }}
    certmanager.k8s.io/acme-dns01-provider: clouddns
    certmanager.k8s.io/acme-challenge-type: dns01
    {{- end}}

    {{- if .Values.networking.whitelist }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.networking.whitelist }}
    {{- end}}
spec:
  tls:
    - hosts:
        - {{ .Values.networking.dns }}
      secretName: {{ template "fullname" . }}-cert
  rules:
    - host: {{ .Values.networking.dns }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "fullname" . }}
              servicePort: 80
