apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  annotations:
  labels:
    app: {{ template "fullname" . }}
{{- if .Values.global.labels }}
{{ toYaml .Values.global.labels | indent 4 }}
{{- end }}
spec:
  selector:
    app: {{ template "fullname" . }}
  type: {{ .Values.networking.serviceType }}
  ports:
    - port: 80
      targetPort: {{ .Values.application.port }}
      protocol: TCP
      nodePort: