apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: air-quality-api-ag
  labels:
    app: air-quality-api
    tier: aq-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: air-quality-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 95